export const HERO_ALIASES = {
  // Placeholder, will be populated later
  "dmon": ["디몬"],
  "domina": ["도미나"],
  "doomfist": ["둠", "둠피"],
  "dva": ["디바", "딮"],
  "hazard": ["해저드"],
  "junker-queen": ["정퀸", "퀸"],
  "mauga": ["마우가"],
  "orisa": ["오리사", "올"],
  "ramattra": ["라마", "라맛"],
  "reinhardt": ["라인"],
  "roadhog": ["호그"],
  "sigma": ["시그마", "식"],
  "winston": ["윈", "윈스턴", "원", "원숭이"],
  "wrecking-ball": ["볼", "레킹볼"],
  "zarya": ["자리야", "잘"],
  
  "anran": ["안란"],
  "ashe": ["애쉬", "앸"],
  "bastion": ["바스"],
  "cassidy": ["캐서디", "맥", "맥크리"],
  "echo": ["에코", "엨"],
  "emre": ["엠레"],
  "freja": ["프레야"],
  "genji": ["겐", "겐지"],
  "hanzo": ["한조", "한"],
  "junkrat": ["정크", "정"],
  "mei": ["메이"],
  "pharah": ["파라", "팔"],
  "reaper": ["리퍼", "립"],
  "shion": ["시온"],
  "sierra": ["시에라"],
  "sojourn": ["소전", "솢"],
  "soldier-76": ["솔저", "솔"],
  "sombra": ["솜", "솜브라"],
  "symmetra": ["시메", "심"],
  "torbjorn": ["토르", "톨"],
  "tracer": ["트레", "틀"],
  "vendetta": ["벤데타"],
  "venture": ["벤처", "벤"],
  "widowmaker": ["위도우", "위"],
  
  "ana": ["아나", "안"],
  "baptiste": ["바티", "밥"],
  "brigitte": ["브리", "블"],
  "illari": ["일리아리", "일"],
  "jetpack-cat": ["제트팩캣", "캣"],
  "juno": ["주노", "준"],
  "kiriko": ["키리코", "킬"],
  "lifeweaver": ["라이프위버", "라위"],
  "lucio": ["루시우", "루"],
  "mercy": ["메르시", "멜"],
  "mizuki": ["미즈키"],
  "moira": ["모이라", "모"],
  "wuyang": ["우양"],
  "zenyatta": ["젠야타", "젠"]
};
