export const HERO_ALIASES = {
  // Tank
  "dmon": ["디몬", "디", "Dmon", "dmon"],
  "dva": ["디바", "디", "dva"],
  "doomfist": ["둠"],
  "wrecking-ball": ["볼"],
  "winston": ["윈"],
  "hazard": ["해"],
  "mauga": ["마"],
  "orisa": ["오"],
  "domina": ["도"],
  "sigma": ["시"],
  "junker-queen": ["퀸"],
  "zarya": ["자"],
  "reinhardt": ["라인", "라"],
  "ramattra": ["라마", "라"],
  "roadhog": ["호그", "호"],
  
  // Damage
  "mei": ["메"],
  "bastion": ["바", "바스"],
  "soldier-76": ["솔"],
  "symmetra": ["시", "시메"],
  "emre": ["엠레", "엠"],
  "junkrat": ["정크", "정"],
  "torbjorn": ["토르", "톨비", "토"],
  "sombra": ["솜"],
  "sierra": ["시"],
  "echo": ["에"],
  "pharah": ["파"],
  "freja": ["프"],
  "genji": ["겐"],
  "reaper": ["리"],
  "vendetta": ["벤"],
  "venture": ["벤"],
  "shion": ["시"],
  "anran": ["안"],
  "tracer": ["트", "트레"],
  "sojourn": ["소"],
  "ashe": ["애"],
  "widowmaker": ["위", "위도우"],
  "cassidy": ["캐", "맥", "맥크리"],
  "hanzo": ["한"],
  
  // Support
  "lucio": ["루"],
  "baptiste": ["바", "바티"],
  "ana": ["아"],
  "jetpack-cat": ["캣", "냥"],
  "zenyatta": ["젠"],
  "lifeweaver": ["라", "위", "라위"],
  "mercy": ["메"],
  "moira": ["모"],
  "kiriko": ["키"],
  "mizuki": ["미"],
  "brigitte": ["브리"],
  "wuyang": ["우"],
  "illari": ["일"],
  "juno": ["주"]
};
